### PR TITLE
Add skip_host_key_verification

### PR DESCRIPTION
**Pull request by takumakanari**
This p-r adds new booi option to skip HostKey verification.

### CODE REVIEW

**Comment by kamatama41** [comment]
Thank you for your contribution!
I'll release it as 0.1.9 soon.

**Comment by takumakanari** [comment]
Thanks very much!

**Comment by kamatama41** [comment]
@takumakanari 
I've released 0.1.9 to RubyGems.org.
Please check, thanks 😃

**Comment by takumakanari** [comment]
@kamatama41 Thanks. I confirmed.

**Pull request merged**
